<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Faker\Factory as Faker;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $desContent = '
        <h2>Course Descriptions</h2>
        <p>If you’re learning to program for the first time, or if you’re coming from a different language, this course, JavaScript: Getting Started, will give you the basics for coding in JavaScript. First, you\'ll discover the types of applications that can be built with JavaScript, and the platforms they’ll run on.</p>
        <p>Next, you’ll explore the basics of the language, giving plenty of examples. Lastly, you’ll put your JavaScript knowledge to work and modify a modern, responsive web page. When you’re finished with this course, you’ll have the skills and knowledge in JavaScript to create simple programs, create simple web applications, and modify web pages.</p>
        <h3>What you’ll learn</h3>
        <ul>
            <li>Recognize the importance of understanding your objectives when addressing an audience.</li>
            <li>Identify the fundaments of composing a successful close.</li>
            <li>Explore how to connect with your audience through crafting compelling stories.</li>
            <li>Examine ways to connect with your audience by personalizing your content.</li>
            <li>Break down the best ways to exude executive presence.</li>
            <li>Explore how to communicate the unknown in an impromptu communication.</li>
        </ul>
        <p>Maecenas viverra condimentum nulla molestie condimentum. Nunc ex libero, feugiat quis lectus vel, ornare euismod ligula. Aenean sit amet arcu nulla.</p>
        <p>Duis facilisis ex a urna blandit ultricies. Nullam sagittis ligula non eros semper, nec mattis odio ullamcorper. Phasellus feugiat sit amet leo eget consectetur.</p>
    ';
        $faqContent = "<h1>Course - Frequently Asked Questions</h1>

    <h2>How this course help me to design layout?</h2>
    <p>
        My name is Jason Woo and I work as human duct tape at Gatsby, that means that I do a lot of different things. 
        Everything from dev roll to writing content to writing code. And I used to work as an architect at IBM. 
        I live in Portland, Oregon.
    </p>

    <h2>What is important of this course?</h2>
    <p>
        We'll dive into GraphQL, the fundamentals of GraphQL. We're only gonna use the pieces of it that we need to build in Gatsby. 
        We're not gonna be doing a deep dive into what GraphQL is or the language specifics. We're also gonna get into MDX. 
        MDX is a way to write React components in your markdown.
    </p>

    <h2>Why Take This Course?</h2>
    <p>
        We'll dive into GraphQL, the fundamentals of GraphQL. We're only gonna use the pieces of it that we need to build in Gatsby. 
        We're not gonna be doing a deep dive into what GraphQL is or the language specifics. We're also gonna get into MDX. 
        MDX is a way to write React components in your markdown.
    </p>

    <h2>Is able to create application after this course?</h2>
    <p>
        We'll dive into GraphQL, the fundamentals of GraphQL. We're only gonna use the pieces of it that we need to build in Gatsby. 
        We're not gonna be doing a deep dive into what GraphQL is or the language specifics. We're also gonna get into MDX. 
        MDX is a way to write React components in your markdown.
    </p>";
        DB::table('course')->insert(
            [
                [
                    'name' => 'React',
                    'title' => 'How to easily create a website with React',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/abPmZCZZrFA?si=ZzepLbKfuKv3OFFU',
                    'image' => 'course-react.jpg',
                    'preview' => 'React is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Angular',
                    'title' => 'Angular - the complete guide for beginner',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/xypzmu5mMPY?si=jbsbTYIGETsJ_GWr',
                    'image' => 'course-angular.jpg',
                    'preview' => 'Angular is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'React',
                    'title' => 'How to easily create a website with React',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/abPmZCZZrFA?si=ZzepLbKfuKv3OFFU',
                    'image' => 'course-react.jpg',
                    'preview' => 'React is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Angular',
                    'title' => 'Angular - the complete guide for beginner',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/xypzmu5mMPY?si=jbsbTYIGETsJ_GWr',
                    'image' => 'course-angular.jpg',
                    'preview' => 'Angular is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Python',
                    'title' => 'The Python Course: build web application',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/HXkh7EOqcQ4?si=57vg5Sh39z1udppJ',
                    'image' => 'course-python.jpg',
                    'preview' => 'Python is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'GraphQL',
                    'title' => 'GraphQL: introduction to graphQL for beginners',
                    'level' => 'Advance',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/HCjNJDNzw8Y?si=DLsS-lDtqvsKubk6',
                    'image' => 'course-graphql.jpg',
                    'preview' => 'GraphQL is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Python',
                    'title' => 'The Python Course: build web application',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/HXkh7EOqcQ4?si=57vg5Sh39z1udppJ',
                    'image' => 'course-python.jpg',
                    'preview' => 'Python is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'GraphQL',
                    'title' => 'GraphQL: introduction to graphQL for beginners',
                    'level' => 'Advance',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/HCjNJDNzw8Y?si=DLsS-lDtqvsKubk6',
                    'image' => 'course-graphql.jpg',
                    'preview' => 'GraphQL is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'JavaScript',
                    'title' => 'Getting Started with JavaScript',
                    'level' => 'Advance',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/aezstCBHOPQ?si=cCAvs5Stuo6LZE6U',
                    'image' => 'course-javascript.jpg',
                    'preview' => 'JavaScript is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CSS3',
                    'title' => 'CSS: ultimate CSS course from beginner to advanced',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/m6_GrrcGTNg?si=FXmHrb5-FLTFEwS_',
                    'image' => 'course-css.jpg',
                    'preview' => 'CSS3 is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'JavaScript',
                    'title' => 'Getting Started with JavaScript',
                    'level' => 'Advance',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/aezstCBHOPQ?si=cCAvs5Stuo6LZE6U',
                    'image' => 'course-javascript.jpg',
                    'preview' => 'JavaScript is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'CSS3',
                    'title' => 'CSS: ultimate CSS course from beginner to advanced',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/m6_GrrcGTNg?si=FXmHrb5-FLTFEwS_',
                    'image' => 'course-css.jpg',
                    'preview' => 'CSS3 is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Wordpress',
                    'title' => 'Wordpress: complete WordPress theme & plugin development',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/HPL74s4VPdk?si=Rk_uEW2ZIvSGJT2J',
                    'image' => 'course-wordpress.jpg',
                    'preview' => 'Wordpress is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Gatsby',
                    'title' => 'Gatsby JS: build blog with GraphQL and React',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/i8_w_m6HLJ0?si=sRPweJS4nRpq_yip',
                    'image' => 'course-gatsby.jpg',
                    'preview' => 'Gatsby is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C',
                    'title' => 'C : Open the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c.jpg',
                    'preview' => 'C is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C++',
                    'title' => 'C++ : Open the next step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c++.jpg',
                    'preview' => 'C++ is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C#',
                    'title' => 'C : Open the last step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c#.jpg',
                    'preview' => 'C# is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C',
                    'title' => 'C : Open the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c.jpg',
                    'preview' => 'C is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C++',
                    'title' => 'C++ : Open the next step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c++.jpg',
                    'preview' => 'C++ is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C#',
                    'title' => 'C : Open the last step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c#.jpg',
                    'preview' => 'C# is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C',
                    'title' => 'C : Open the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c.jpg',
                    'preview' => 'C is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C++',
                    'title' => 'C++ : Open the next step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c++.jpg',
                    'preview' => 'C++ is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'C#',
                    'title' => 'C : Open the last step of the world of IT',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-c#.jpg',
                    'preview' => 'C# is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vue.js',
                    'title' => 'Vue.js Components Fundamentals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-vue.jpg',
                    'preview' => 'Vue.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vue.js',
                    'title' => 'Vue.js Components Fundamentals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-vue.jpg',
                    'preview' => 'Vue.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vue.js',
                    'title' => 'Vue.js Components Fundamentals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-vue.jpg',
                    'preview' => 'Vue.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Vue.js',
                    'title' => 'Vue.js Components Fundamentals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-vue.jpg',
                    'preview' => 'Vue.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Node.js',
                    'title' => 'Node.js Tutorials - For beginners and professionals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-node.jpg',
                    'preview' => 'Node.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Node.js',
                    'title' => 'Node.js Tutorials - For beginners and professionals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-node.jpg',
                    'preview' => 'Node.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Node.js',
                    'title' => 'Node.js Tutorials - For beginners and professionals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-node.jpg',
                    'preview' => 'Node.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Node.js',
                    'title' => 'Node.js Tutorials - For beginners and professionals',
                    'level' => 'Beginner',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-node.jpg',
                    'preview' => 'Node.js is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Laravel',
                    'title' => 'Building Scalable APIs with Laravel',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-laravel.jpg',
                    'preview' => 'Laravel is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sass',
                    'title' => 'Sass Web Front End Development',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-sass.jpg',
                    'preview' => 'Sass is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 4,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Laravel',
                    'title' => 'Building Scalable APIs with Laravel',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-laravel.jpg',
                    'preview' => 'Laravel is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sass',
                    'title' => 'Sass Web Front End Development',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-sass.jpg',
                    'preview' => 'Sass is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 3,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Laravel',
                    'title' => 'Building Scalable APIs with Laravel',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-laravel.jpg',
                    'preview' => 'Laravel is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sass',
                    'title' => 'Sass Web Front End Development',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-sass.jpg',
                    'preview' => 'Sass is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 2,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Laravel',
                    'title' => 'Building Scalable APIs with Laravel',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-laravel.jpg',
                    'preview' => 'Laravel is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'name' => 'Sass',
                    'title' => 'Sass Web Front End Development',
                    'level' => 'Intermediate',
                    'description' => $desContent,
                    'course_media' => 'https://youtu.be/IxSJzB7rAes?si=cCtei7Xl2CKGkMF1',
                    'image' => 'course-sass.jpg',
                    'preview' => 'Sass is the popular programming language which powers web pages and web applications. This course will get you started coding in JavaScript.',
                    'faq' => $faqContent,
                    'price' => rand(1000, 10000),
                    'instructor_id' => rand(1,6),
                    'course_cate_id' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
